## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file math_thesis.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_26 = Integer(26); _sage_const_100 = Integer(100); _sage_const_30 = Integer(30); _sage_const_33 = Integer(33); _sage_const_0 = Integer(0); _sage_const_36 = Integer(36); _sage_const_1 = Integer(1); _sage_const_44 = Integer(44); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50); _sage_const_55 = Integer(55); _sage_const_63 = Integer(63); _sage_const_4 = Integer(4); _sage_const_70 = Integer(70); _sage_const_73 = Integer(73); _sage_const_76 = Integer(76); _sage_const_3 = Integer(3)## This file (math_thesis.sagetex.sage) was *autogenerated* from math_thesis.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('math_thesis', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_26 
_st_.blockbegin()
try:
 n = _sage_const_100 
 partitions = number_of_partitions(n)
 factors = factor(partitions)
except:
 _st_.goboom(_sage_const_30 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_0 , latex(partitions))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.inline(_sage_const_1 , latex(factors))
except:
 _st_.goboom(_sage_const_36 )
_st_.current_tex_line = _sage_const_44 
_st_.blockbegin()
try:
 var('x, y')
 # We use sagesilent because we don't want the plotting code
 # to appear in the final text, only the image.
 p = plot3d(sin(x**_sage_const_2  + y**_sage_const_2 ), (x, -_sage_const_2 , _sage_const_2 ), (y, -_sage_const_2 , _sage_const_2 ),
            adaptive=True, color='automatic')
except:
 _st_.goboom(_sage_const_50 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_55 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_55 )
_st_.current_tex_line = _sage_const_63 
_st_.blockbegin()
try:
 # Polynomial factorization
 poly = x**_sage_const_4  - _sage_const_1 
 factored = factor(poly)
 
 # Symbolic integration
 integral_result = integrate(sin(x)**_sage_const_2 , x)
except:
 _st_.goboom(_sage_const_70 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_2 , latex(factored))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_76 
 _st_.inline(_sage_const_3 , latex(integral_result))
except:
 _st_.goboom(_sage_const_76 )
_st_.endofdoc()

